$(document).ready(function(){

    $(".plant_home").mouseenter(function(){
        $(".plant_home").addClass("hover");
    });
    $(".plant_home").mouseleave(function(){
        $(".plant_home").removeClass("hover");
    });
    $(".seed").mouseenter(function(){
        $(".seed").addClass("seed_wiggle");
    });
    $(".seed").mouseleave(function(){
        $(".seed").removeClass("seed_wiggle");
    });
    $(".watering_can").mouseenter(function(){
        $(".watering_can").addClass("can_interact");
    });
    $(".watering_can").mouseleave(function(){
        $(".watering_can").removeClass("can_interact");
    });
    $(".blank").mouseenter(function(){
        $(".plant_room3").addClass("hover");
    });
    $(".blank").mouseleave(function(){
        $(".plant_room3").removeClass("hover");
    });
    $("#book_5").mouseenter(function(){
        $("#book_5").addClass("book_5_bounce");
    });
    $("#book_5").mouseleave(function(){
        $("#book_5").removeClass("book_5_bounce");
    });
});